// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package program

import (
	"api-gateway/api/program"
)

type ControllerV1 struct{}

func NewV1() program.IProgramV1 {
	return &ControllerV1{}
}
