// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package upstream

import (
	"api-gateway/api/upstream"
)

type ControllerV1 struct{}

func NewV1() upstream.IUpstreamV1 {
	return &ControllerV1{}
}
